"""
TPC-H Benchmark Golden Queries (Q1-Q22)

This module contains all 22 TPC-H decision support benchmark queries
parsed from the PostgreSQL implementation.

Each query includes:
- id: Query identifier (Q1-Q22)
- name: Descriptive name
- question: Natural language business question
- golden_sql: Complete SQL query
- category: Query type (basic/aggregation/complex)
- complexity: Estimated complexity (low/medium/high)

Source: PostgreSQL implementation from Vonng/pgtpc GitHub repository
"""

TPCH_GOLDEN_QUERIES = [
    {
        "id": "Q1",
        "name": "Pricing Summary Report",
        "question": "What are the summary pricing statistics for line items grouped by return flag and status?",
        "golden_sql": """
SELECT
    l_returnflag,
    l_linestatus,
    SUM(l_quantity) AS sum_qty,
    SUM(l_extendedprice) AS sum_base_price,
    SUM(l_extendedprice * (1 - l_discount)) AS sum_disc_price,
    SUM(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge,
    AVG(l_quantity) AS avg_qty,
    AVG(l_extendedprice) AS avg_price,
    AVG(l_discount) AS avg_disc,
    COUNT(*) AS count_order
FROM lineitem
WHERE l_shipdate <= DATE '1998-12-01' - INTERVAL '90' DAY
GROUP BY l_returnflag, l_linestatus
ORDER BY l_returnflag, l_linestatus
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q2",
        "name": "Minimum Cost Supplier",
        "question": "Which suppliers in Europe can supply a specific brass part at the minimum cost?",
        "golden_sql": """
SELECT
    s_acctbal,
    s_name,
    n_name,
    p_partkey,
    p_mfgr,
    s_address,
    s_phone,
    s_comment
FROM part, supplier, partsupp, nation, region
WHERE
    p_partkey = ps_partkey
    AND s_suppkey = ps_suppkey
    AND p_size = 15
    AND p_type LIKE '%BRASS'
    AND s_nationkey = n_nationkey
    AND n_regionkey = r_regionkey
    AND r_name = 'EUROPE'
    AND ps_supplycost = (
        SELECT MIN(ps_supplycost)
        FROM partsupp, supplier, nation, region
        WHERE
            p_partkey = ps_partkey
            AND s_suppkey = ps_suppkey
            AND s_nationkey = n_nationkey
            AND n_regionkey = r_regionkey
            AND r_name = 'EUROPE'
    )
ORDER BY s_acctbal DESC, n_name, s_name, p_partkey
LIMIT 100
""",
        "category": "complex",
        "complexity": "high",
    },
    {
        "id": "Q3",
        "name": "Shipping Priority",
        "question": "What are the top 10 highest revenue unshipped orders for the building market segment?",
        "golden_sql": """
SELECT
    l_orderkey,
    SUM(l_extendedprice * (1 - l_discount)) AS revenue,
    o_orderdate,
    o_shippriority
FROM customer, orders, lineitem
WHERE
    c_mktsegment = 'BUILDING'
    AND c_custkey = o_custkey
    AND l_orderkey = o_orderkey
    AND o_orderdate < DATE '1995-03-15'
    AND l_shipdate > DATE '1995-03-15'
GROUP BY l_orderkey, o_orderdate, o_shippriority
ORDER BY revenue DESC, o_orderdate
LIMIT 10
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q4",
        "name": "Order Priority Checking",
        "question": "How many orders by priority had at least one line item received after the commit date?",
        "golden_sql": """
SELECT
    o_orderpriority,
    COUNT(*) AS order_count
FROM orders
WHERE
    o_orderdate >= DATE '1993-07-01'
    AND o_orderdate < DATE '1993-07-01' + INTERVAL '3' MONTH
    AND EXISTS (
        SELECT *
        FROM lineitem
        WHERE l_orderkey = o_orderkey AND l_commitdate < l_receiptdate
    )
GROUP BY o_orderpriority
ORDER BY o_orderpriority
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q5",
        "name": "Local Supplier Volume",
        "question": "What is the revenue generated by suppliers in Asia for the year 1994?",
        "golden_sql": """
SELECT
    n_name,
    SUM(l_extendedprice * (1 - l_discount)) AS revenue
FROM customer, orders, lineitem, supplier, nation, region
WHERE
    c_custkey = o_custkey
    AND l_orderkey = o_orderkey
    AND l_suppkey = s_suppkey
    AND c_nationkey = s_nationkey
    AND s_nationkey = n_nationkey
    AND n_regionkey = r_regionkey
    AND r_name = 'ASIA'
    AND o_orderdate >= DATE '1994-01-01'
    AND o_orderdate < DATE '1994-01-01' + INTERVAL '1' YEAR
GROUP BY n_name
ORDER BY revenue DESC
""",
        "category": "complex",
        "complexity": "high",
    },
    {
        "id": "Q6",
        "name": "Forecasting Revenue Change",
        "question": "What is the total revenue from line items with specific discount and quantity constraints in 1994?",
        "golden_sql": """
SELECT SUM(l_extendedprice * l_discount) AS revenue
FROM lineitem
WHERE
    l_shipdate >= DATE '1994-01-01'
    AND l_shipdate < DATE '1994-01-01' + INTERVAL '1' YEAR
    AND l_discount BETWEEN 0.05 AND 0.07
    AND l_quantity < 24
""",
        "category": "aggregation",
        "complexity": "low",
    },
    {
        "id": "Q7",
        "name": "Volume Shipping",
        "question": "What is the shipping volume revenue between France and Germany from 1995-1996?",
        "golden_sql": """
SELECT
    supp_nation,
    cust_nation,
    l_year,
    SUM(volume) AS revenue
FROM (
    SELECT
        n1.n_name AS supp_nation,
        n2.n_name AS cust_nation,
        EXTRACT(YEAR FROM l_shipdate) AS l_year,
        l_extendedprice * (1 - l_discount) AS volume
    FROM supplier, lineitem, orders, customer, nation n1, nation n2
    WHERE
        s_suppkey = l_suppkey
        AND o_orderkey = l_orderkey
        AND c_custkey = o_custkey
        AND s_nationkey = n1.n_nationkey
        AND c_nationkey = n2.n_nationkey
        AND (
            (n1.n_name = 'FRANCE' AND n2.n_name = 'GERMANY')
            OR (n1.n_name = 'GERMANY' AND n2.n_name = 'FRANCE')
        )
        AND l_shipdate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
) AS shipping
GROUP BY supp_nation, cust_nation, l_year
ORDER BY supp_nation, cust_nation, l_year
""",
        "category": "complex",
        "complexity": "high",
    },
    {
        "id": "Q8",
        "name": "National Market Share",
        "question": "What is Brazil's market share for economy anodized steel products in America from 1995-1996?",
        "golden_sql": """
SELECT
    o_year,
    SUM(CASE WHEN nation = 'BRAZIL' THEN volume ELSE 0 END) / SUM(volume) AS mkt_share
FROM (
    SELECT
        EXTRACT(YEAR FROM o_orderdate) AS o_year,
        l_extendedprice * (1 - l_discount) AS volume,
        n2.n_name AS nation
    FROM part, supplier, lineitem, orders, customer, nation n1, nation n2, region
    WHERE
        p_partkey = l_partkey
        AND s_suppkey = l_suppkey
        AND l_orderkey = o_orderkey
        AND o_custkey = c_custkey
        AND c_nationkey = n1.n_nationkey
        AND n1.n_regionkey = r_regionkey
        AND r_name = 'AMERICA'
        AND s_nationkey = n2.n_nationkey
        AND o_orderdate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
        AND p_type = 'ECONOMY ANODIZED STEEL'
) AS all_nations
GROUP BY o_year
ORDER BY o_year
""",
        "category": "complex",
        "complexity": "high",
    },
    {
        "id": "Q9",
        "name": "Product Type Profit Measure",
        "question": "What is the profit by nation and year for parts containing 'green' in their name?",
        "golden_sql": """
SELECT
    nation,
    o_year,
    SUM(amount) AS sum_profit
FROM (
    SELECT
        n_name AS nation,
        EXTRACT(YEAR FROM o_orderdate) AS o_year,
        l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity AS amount
    FROM part, supplier, lineitem, partsupp, orders, nation
    WHERE
        s_suppkey = l_suppkey
        AND ps_suppkey = l_suppkey
        AND ps_partkey = l_partkey
        AND p_partkey = l_partkey
        AND o_orderkey = l_orderkey
        AND s_nationkey = n_nationkey
        AND p_name LIKE '%green%'
) AS profit
GROUP BY nation, o_year
ORDER BY nation, o_year DESC
""",
        "category": "complex",
        "complexity": "high",
    },
    {
        "id": "Q10",
        "name": "Returned Item Reporting",
        "question": "Which customers generated the most revenue from returned items in Q4 1993?",
        "golden_sql": """
SELECT
    c_custkey,
    c_name,
    SUM(l_extendedprice * (1 - l_discount)) AS revenue,
    c_acctbal,
    n_name,
    c_address,
    c_phone,
    c_comment
FROM customer, orders, lineitem, nation
WHERE
    c_custkey = o_custkey
    AND l_orderkey = o_orderkey
    AND o_orderdate >= DATE '1993-10-01'
    AND o_orderdate < DATE '1993-10-01' + INTERVAL '3' MONTH
    AND l_returnflag = 'R'
    AND c_nationkey = n_nationkey
GROUP BY c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment
ORDER BY revenue DESC
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q11",
        "name": "Important Stock Identification",
        "question": "Which parts from German suppliers represent significant inventory value?",
        "golden_sql": """
SELECT
    ps_partkey,
    SUM(ps_supplycost * ps_availqty) AS value
FROM partsupp, supplier, nation
WHERE
    ps_suppkey = s_suppkey
    AND s_nationkey = n_nationkey
    AND n_name = 'GERMANY'
GROUP BY ps_partkey
HAVING SUM(ps_supplycost * ps_availqty) > (
    SELECT SUM(ps_supplycost * ps_availqty) * 0.0001000000
    FROM partsupp, supplier, nation
    WHERE
        ps_suppkey = s_suppkey
        AND s_nationkey = n_nationkey
        AND n_name = 'GERMANY'
)
ORDER BY value DESC
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q12",
        "name": "Shipping Modes and Order Priority",
        "question": "How do shipping modes correlate with order priority for deliveries in 1994?",
        "golden_sql": """
SELECT
    l_shipmode,
    SUM(CASE
        WHEN o_orderpriority = '1-URGENT' OR o_orderpriority = '2-HIGH'
        THEN 1
        ELSE 0
    END) AS high_line_count,
    SUM(CASE
        WHEN o_orderpriority <> '1-URGENT' AND o_orderpriority <> '2-HIGH'
        THEN 1
        ELSE 0
    END) AS low_line_count
FROM orders, lineitem
WHERE
    o_orderkey = l_orderkey
    AND l_shipmode IN ('MAIL', 'SHIP')
    AND l_commitdate < l_receiptdate
    AND l_shipdate < l_commitdate
    AND l_receiptdate >= DATE '1994-01-01'
    AND l_receiptdate < DATE '1994-01-01' + INTERVAL '1' YEAR
GROUP BY l_shipmode
ORDER BY l_shipmode
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q13",
        "name": "Customer Distribution",
        "question": "What is the distribution of customers by order count (excluding special requests)?",
        "golden_sql": """
SELECT
    c_count,
    COUNT(*) AS custdist
FROM (
    SELECT
        c_custkey,
        COUNT(o_orderkey)
    FROM customer
    LEFT OUTER JOIN orders ON
        c_custkey = o_custkey
        AND o_comment NOT LIKE '%special%requests%'
    GROUP BY c_custkey
) AS c_orders (c_custkey, c_count)
GROUP BY c_count
ORDER BY custdist DESC, c_count DESC
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q14",
        "name": "Promotion Effect",
        "question": "What percentage of revenue came from promotional items in September 1995?",
        "golden_sql": """
SELECT
    100.00 * SUM(CASE
        WHEN p_type LIKE 'PROMO%'
        THEN l_extendedprice * (1 - l_discount)
        ELSE 0
    END) / SUM(l_extendedprice * (1 - l_discount)) AS promo_revenue
FROM lineitem, part
WHERE
    l_partkey = p_partkey
    AND l_shipdate >= DATE '1995-09-01'
    AND l_shipdate < DATE '1995-09-01' + INTERVAL '1' MONTH
""",
        "category": "aggregation",
        "complexity": "low",
    },
    {
        "id": "Q15",
        "name": "Top Supplier",
        "question": "Which supplier had the highest total revenue in Q1 1996?",
        "golden_sql": """
WITH revenue0 (supplier_no, total_revenue) AS (
    SELECT
        l_suppkey,
        SUM(l_extendedprice * (1 - l_discount))
    FROM lineitem
    WHERE
        l_shipdate >= DATE '1996-01-01'
        AND l_shipdate < DATE '1996-01-01' + INTERVAL '3' MONTH
    GROUP BY l_suppkey
)
SELECT
    s_suppkey,
    s_name,
    s_address,
    s_phone,
    total_revenue
FROM supplier, revenue0
WHERE
    s_suppkey = supplier_no
    AND total_revenue = (SELECT MAX(total_revenue) FROM revenue0)
ORDER BY s_suppkey
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q16",
        "name": "Parts/Supplier Relationship",
        "question": "How many suppliers can provide each part configuration (excluding problem suppliers)?",
        "golden_sql": """
SELECT
    p_brand,
    p_type,
    p_size,
    COUNT(DISTINCT ps_suppkey) AS supplier_cnt
FROM partsupp, part
WHERE
    p_partkey = ps_partkey
    AND p_brand <> 'Brand#45'
    AND p_type NOT LIKE 'MEDIUM POLISHED%'
    AND p_size IN (49, 14, 23, 45, 19, 3, 36, 9)
    AND ps_suppkey NOT IN (
        SELECT s_suppkey
        FROM supplier
        WHERE s_comment LIKE '%Customer%Complaints%'
    )
GROUP BY p_brand, p_type, p_size
ORDER BY supplier_cnt DESC, p_brand, p_type, p_size
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q17",
        "name": "Small-Quantity-Order Revenue",
        "question": "What is the average annual revenue for small quantity orders of a specific brand/container?",
        "golden_sql": """
SELECT SUM(l_extendedprice) / 7.0 AS avg_yearly
FROM lineitem, part
WHERE
    p_partkey = l_partkey
    AND p_brand = 'Brand#23'
    AND p_container = 'MED BOX'
    AND l_quantity < (
        SELECT 0.2 * AVG(l_quantity)
        FROM lineitem
        WHERE l_partkey = p_partkey
    )
""",
        "category": "complex",
        "complexity": "medium",
    },
    {
        "id": "Q18",
        "name": "Large Volume Customer",
        "question": "Which customers placed orders with more than 300 total items?",
        "golden_sql": """
SELECT
    c_name,
    c_custkey,
    o_orderkey,
    o_orderdate,
    o_totalprice,
    SUM(l_quantity)
FROM customer, orders, lineitem
WHERE
    o_orderkey IN (
        SELECT l_orderkey
        FROM lineitem
        GROUP BY l_orderkey
        HAVING SUM(l_quantity) > 300
    )
    AND c_custkey = o_custkey
    AND o_orderkey = l_orderkey
GROUP BY c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice
ORDER BY o_totalprice DESC, o_orderdate
""",
        "category": "aggregation",
        "complexity": "medium",
    },
    {
        "id": "Q19",
        "name": "Discounted Revenue",
        "question": "What is the revenue from specific brand/container/quantity combinations with air shipment?",
        "golden_sql": """
SELECT SUM(l_extendedprice * (1 - l_discount)) AS revenue
FROM lineitem, part
WHERE
    (
        p_partkey = l_partkey
        AND p_brand = 'Brand#12'
        AND p_container IN ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
        AND l_quantity >= 1 AND l_quantity <= 11
        AND p_size BETWEEN 1 AND 5
        AND l_shipmode IN ('AIR', 'AIR REG')
        AND l_shipinstruct = 'DELIVER IN PERSON'
    )
    OR (
        p_partkey = l_partkey
        AND p_brand = 'Brand#23'
        AND p_container IN ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
        AND l_quantity >= 10 AND l_quantity <= 20
        AND p_size BETWEEN 1 AND 10
        AND l_shipmode IN ('AIR', 'AIR REG')
        AND l_shipinstruct = 'DELIVER IN PERSON'
    )
    OR (
        p_partkey = l_partkey
        AND p_brand = 'Brand#34'
        AND p_container IN ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
        AND l_quantity >= 20 AND l_quantity <= 30
        AND p_size BETWEEN 1 AND 15
        AND l_shipmode IN ('AIR', 'AIR REG')
        AND l_shipinstruct = 'DELIVER IN PERSON'
    )
""",
        "category": "complex",
        "complexity": "high",
    },
    {
        "id": "Q20",
        "name": "Potential Part Promotion",
        "question": "Which Canadian suppliers have excess inventory of forest parts based on 1994 shipment history?",
        "golden_sql": """
SELECT s_name, s_address
FROM supplier, nation
WHERE
    s_suppkey IN (
        SELECT ps_suppkey
        FROM partsupp
        WHERE
            ps_partkey IN (
                SELECT p_partkey
                FROM part
                WHERE p_name LIKE 'forest%'
            )
            AND ps_availqty > (
                SELECT 0.5 * SUM(l_quantity)
                FROM lineitem
                WHERE
                    l_partkey = ps_partkey
                    AND l_suppkey = ps_suppkey
                    AND l_shipdate >= DATE '1994-01-01'
                    AND l_shipdate < DATE '1994-01-01' + INTERVAL '1' YEAR
            )
    )
    AND s_nationkey = n_nationkey
    AND n_name = 'CANADA'
ORDER BY s_name
""",
        "category": "complex",
        "complexity": "high",
    },
    {
        "id": "Q21",
        "name": "Suppliers Who Kept Orders Waiting",
        "question": "Which Saudi Arabian suppliers had late deliveries where they were the only late supplier on multi-supplier orders?",
        "golden_sql": """
SELECT
    s_name,
    COUNT(*) AS numwait
FROM supplier, lineitem l1, orders, nation
WHERE
    s_suppkey = l1.l_suppkey
    AND o_orderkey = l1.l_orderkey
    AND o_orderstatus = 'F'
    AND l1.l_receiptdate > l1.l_commitdate
    AND EXISTS (
        SELECT *
        FROM lineitem l2
        WHERE
            l2.l_orderkey = l1.l_orderkey
            AND l2.l_suppkey <> l1.l_suppkey
    )
    AND NOT EXISTS (
        SELECT *
        FROM lineitem l3
        WHERE
            l3.l_orderkey = l1.l_orderkey
            AND l3.l_suppkey <> l1.l_suppkey
            AND l3.l_receiptdate > l3.l_commitdate
    )
    AND s_nationkey = n_nationkey
    AND n_name = 'SAUDI ARABIA'
GROUP BY s_name
ORDER BY numwait DESC, s_name
LIMIT 100
""",
        "category": "complex",
        "complexity": "high",
    },
    {
        "id": "Q22",
        "name": "Global Sales Opportunity",
        "question": "What is the count and total account balance of customers in specific countries with above-average balances but no orders?",
        "golden_sql": """
SELECT
    cntrycode,
    COUNT(*) AS numcust,
    SUM(c_acctbal) AS totacctbal
FROM (
    SELECT
        SUBSTRING(c_phone FROM 1 FOR 2) AS cntrycode,
        c_acctbal
    FROM customer
    WHERE
        SUBSTRING(c_phone FROM 1 FOR 2) IN ('13', '31', '23', '29', '30', '18', '17')
        AND c_acctbal > (
            SELECT AVG(c_acctbal)
            FROM customer
            WHERE
                c_acctbal > 0.00
                AND SUBSTRING(c_phone FROM 1 FOR 2) IN ('13', '31', '23', '29', '30', '18', '17')
        )
        AND NOT EXISTS (
            SELECT *
            FROM orders
            WHERE o_custkey = c_custkey
        )
) AS custsale
GROUP BY cntrycode
ORDER BY cntrycode
""",
        "category": "complex",
        "complexity": "high",
    },
]


def get_query_by_id(query_id: str) -> dict:
    """Retrieve a specific query by its ID (e.g., 'Q1')."""
    for query in TPCH_GOLDEN_QUERIES:
        if query["id"] == query_id:
            return query
    return None


def get_queries_by_category(category: str) -> list:
    """Retrieve all queries of a specific category."""
    return [q for q in TPCH_GOLDEN_QUERIES if q["category"] == category]


def get_queries_by_complexity(complexity: str) -> list:
    """Retrieve all queries of a specific complexity level."""
    return [q for q in TPCH_GOLDEN_QUERIES if q["complexity"] == complexity]


if __name__ == "__main__":
    print(f"Total TPC-H Golden Queries: {len(TPCH_GOLDEN_QUERIES)}")
    print("\nQuery Distribution:")

    categories = {}
    complexities = {}

    for query in TPCH_GOLDEN_QUERIES:
        cat = query["category"]
        comp = query["complexity"]
        categories[cat] = categories.get(cat, 0) + 1
        complexities[comp] = complexities.get(comp, 0) + 1

    print("\nBy Category:")
    for cat, count in sorted(categories.items()):
        print(f"  {cat}: {count}")

    print("\nBy Complexity:")
    for comp, count in sorted(complexities.items()):
        print(f"  {comp}: {count}")

    print("\nQuery List:")
    for query in TPCH_GOLDEN_QUERIES:
        print(f"  {query['id']}: {query['name']} ({query['category']}/{query['complexity']})")
